  RAW_MODEL_PATH="/workspace/raw_model"
  BOOSTER_DIR="/workspace/Booster"
  OUTPUT_DIR="/workspace/output"
  DATA_DIR="/workspace/cs_capstone/data"
  CONDA_SH=""
  CONDA_ENV=""
  M1_LORA_PATH="${OUTPUT_DIR}/m1_lora"
